### ISSUE TITLE
Callout Location vs. Location of Racers

### ISSUE THREAD

**Issue by lfpayne** [Zulfurix/FivePD-StreetRace#1]
I'm not sure if this is intentional or not, I didn't see it documented anywhere, but in the event that it isn't...

On our server, we're experiencing the yellow callout circle taking the responding officer to a great distance from where the actual street race vehicles spawn, and the vehicles don't seem to come toward the circle either.

Initially we thought the script did not work altogether however, we once noticed red dots in the Vinewood Hills while the yellow marker was up, so prior to proceeding to the yellow marker the responding officer went to the red dots and found the AI lined up. Another officer came and kept them in line of sight while the responding officer went to the yellow circle to trigger the race.

This has been pretty consistent for us.

**Comment by Zulfurix** [comment]
Hi, apologies for the long delay! 

I'll definitely get a look into this as soon as possible! Thanks for bringing it up.
